"""Add abacate column to client table

Revision ID: da705bb019dc
Revises: e4e994642cd7
Create Date: 2024-05-31 10:56:14.786671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da705bb019dc'
down_revision: Union[str, None] = 'e4e994642cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('abacate', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'abacate')
    # ### end Alembic commands ###
